# Generated by Django 5.2a1 on 2025-10-19 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YoloModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("date_built", models.DateField(default=django.utils.timezone.now)),
                ("base_model", models.CharField(max_length=50)),
                (
                    "num_params",
                    models.BigIntegerField(help_text="Number of parameters"),
                ),
                ("map", models.FloatField(blank=True, null=True)),
                ("map_5095", models.FloatField(blank=True, null=True)),
                ("size", models.CharField(help_text="e.g. '23.1 MB'", max_length=50)),
                (
                    "weights_path",
                    models.CharField(
                        help_text="Absolute path to .pt/.onnx", max_length=512
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-is_active", "-date_built", "name"],
            },
        ),
    ]
